apiVersion: 1

datasources:
  - name: MySQL
    uid: mysql-beeweight
    type: mysql
    access: proxy
    isDefault: true
    url: mysql:3306
    user: ${MYSQL_USER}
    jsonData:
      database: ${MYSQL_DATABASE}
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    secureJsonData:
      password: ${MYSQL_PASSWORD}
